# Generated by Django 6.0 on 2025-12-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventchecklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventchecklist',
            options={'ordering': ['due_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(blank=True, default='General', help_text='e.g., Venue, Catering, Entertainment, Marketing', max_length=100),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, help_text='Date of expense', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, help_text='Estimated/planned cost for this item', max_digits=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='expected_budget',
            field=models.DecimalField(decimal_places=2, help_text='Total approved/expected budget for this event', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Actual amount spent', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget_item',
            field=models.ForeignKey(blank=True, help_text='Link to budget item if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='events.budgetitem'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(help_text='Expense description', max_length=255),
        ),
    ]
